export const services = [
  {
    slug: 'business-loan',
    title: 'Business Loan',
    shortDesc: 'Get collateral-free business loans up to ₹50 Lakhs with competitive interest rates.',
    iconName: 'Banknote',
    color: 'blue',
    heroDesc: 'Access quick and hassle-free business loans to fuel your company\'s growth. We connect you with the best lenders offering competitive rates, flexible tenures, and minimal documentation.',
    features: [
      'Loans from ₹1 Lakh to ₹50 Lakhs',
      'Interest rates starting from 10.5% p.a.',
      'Flexible repayment tenure up to 5 years',
      'Minimal documentation required',
      'Quick disbursement within 7-14 days',
      'No collateral required for eligible businesses',
    ],
    eligibility: [
      'Business operational for at least 2 years',
      'Minimum annual turnover of ₹10 Lakhs',
      'CIBIL score of 650+',
      'Valid GST registration',
      'ITR filed for last 2 years',
    ],
    process: [
      { step: 1, title: 'Consultation', desc: 'Free assessment of your funding needs and eligibility' },
      { step: 2, title: 'Documentation', desc: 'We help prepare and organize all required documents' },
      { step: 3, title: 'Application', desc: 'Submit to the best-matched lender for your profile' },
      { step: 4, title: 'Approval', desc: 'Follow up and negotiate the best terms on your behalf' },
      { step: 5, title: 'Disbursement', desc: 'Funds credited to your account' },
    ],
  },
  {
    slug: 'msme-funding',
    title: 'MSME Funding',
    shortDesc: 'Government-backed MSME schemes with subsidized interest and collateral-free options.',
    iconName: 'Building2',
    color: 'green',
    heroDesc: 'Leverage India\'s robust MSME support ecosystem. We help micro, small, and medium enterprises access government-subsidized funding with lower interest rates and relaxed eligibility criteria.',
    features: [
      'Government subsidized interest rates',
      'Collateral-free loans under CGTMSE',
      'Udyam Registration assistance',
      'Working capital and term loan options',
      'Priority sector lending benefits',
      'Special schemes for women entrepreneurs',
    ],
    eligibility: [
      'Valid Udyam Registration certificate',
      'Business categorized as Micro, Small, or Medium',
      'Manufacturing or service sector entity',
      'No default history with any bank/NBFC',
      'Proper books of accounts maintained',
    ],
    process: [
      { step: 1, title: 'MSME Classification', desc: 'Determine your business category and applicable schemes' },
      { step: 2, title: 'Udyam Registration', desc: 'Assist with registration if not already done' },
      { step: 3, title: 'Scheme Selection', desc: 'Identify the best government scheme for your needs' },
      { step: 4, title: 'Application Filing', desc: 'Complete documentation and apply through proper channel' },
      { step: 5, title: 'Funding Secured', desc: 'Approval and fund disbursement' },
    ],
  },
  {
    slug: 'startup-seed-fund',
    title: 'Startup Seed Fund',
    shortDesc: 'Access SISFS seed funding up to ₹50 Lakhs for DPIIT-recognized startups.',
    iconName: 'Rocket',
    color: 'purple',
    heroDesc: 'The Startup India Seed Fund Scheme (SISFS) provides financial assistance to startups for proof of concept, prototype development, product trials, and market entry. We help you navigate the entire application process.',
    features: [
      'Up to ₹50 Lakhs for proof of concept',
      'Up to ₹25 Lakhs as grants for validation',
      'Government of India backed scheme',
      'No equity dilution for grant component',
      'Mentorship and incubator connections',
      'Follow-on funding facilitation',
    ],
    eligibility: [
      'DPIIT recognized startup',
      'Incorporated not more than 2 years ago',
      'Not received more than ₹10 Lakhs funding',
      'Innovative and scalable business model',
      'Indian citizen founders (51%+ shareholding)',
    ],
    process: [
      { step: 1, title: 'DPIIT Registration', desc: 'Ensure startup is recognized under Startup India' },
      { step: 2, title: 'Incubator Selection', desc: 'Apply through approved incubators' },
      { step: 3, title: 'Pitch Preparation', desc: 'Develop compelling pitch deck and business plan' },
      { step: 4, title: 'Expert Committee', desc: 'Present before the selection committee' },
      { step: 5, title: 'Fund Disbursement', desc: 'Milestone-based fund release' },
    ],
  },
  {
    slug: 'cgtmse',
    title: 'CGTMSE Loan',
    shortDesc: 'Collateral-free credit up to ₹5 Crore under the Credit Guarantee Fund Trust scheme.',
    iconName: 'Shield',
    color: 'teal',
    heroDesc: 'The Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE) scheme enables entrepreneurs to access credit without collateral or third-party guarantee. We maximize your approval chances.',
    features: [
      'Collateral-free loans up to ₹5 Crore',
      'No third-party guarantee required',
      'Available for both new and existing units',
      'Covers manufacturing and service sectors',
      'Guarantee coverage up to 85%',
      'Available through all scheduled commercial banks',
    ],
    eligibility: [
      'Micro or Small Enterprise as per MSMED Act',
      'New or existing manufacturing/service unit',
      'No existing credit facility above ₹5 Crore',
      'Account classified as Standard (no NPA)',
      'Valid Udyam Registration',
    ],
    process: [
      { step: 1, title: 'Eligibility Check', desc: 'Verify your enterprise qualifies under CGTMSE' },
      { step: 2, title: 'Bank Selection', desc: 'Choose the right bank based on your profile' },
      { step: 3, title: 'Documentation', desc: 'Prepare project report and financial documents' },
      { step: 4, title: 'Guarantee Application', desc: 'Bank applies for guarantee coverage' },
      { step: 5, title: 'Loan Sanctioned', desc: 'Collateral-free credit approved and disbursed' },
    ],
  },
  {
    slug: 'pmegp',
    title: 'PMEGP Scheme',
    shortDesc: 'Get up to 35% subsidy on project cost for setting up new micro-enterprises.',
    iconName: 'Landmark',
    color: 'orange',
    heroDesc: 'The Prime Minister\'s Employment Generation Programme (PMEGP) provides subsidies up to 35% on project costs for setting up new manufacturing and service units. We handle the complete application lifecycle.',
    features: [
      'Subsidy up to 35% for special categories',
      'Subsidy up to 25% for general category',
      'Maximum project cost ₹50 Lakhs (manufacturing)',
      'Maximum project cost ₹20 Lakhs (service)',
      'Margin money from government',
      'Bank loan at subsidized rates',
    ],
    eligibility: [
      'Individual above 18 years of age',
      'Minimum 8th pass for projects above ₹10 Lakhs',
      'No prior government subsidy availed',
      'Self Help Groups also eligible',
      'New projects only (no existing businesses)',
    ],
    process: [
      { step: 1, title: 'Eligibility Assessment', desc: 'Check if you qualify for PMEGP subsidy' },
      { step: 2, title: 'Project Report', desc: 'Detailed DPR preparation with financials' },
      { step: 3, title: 'Online Application', desc: 'Apply through KVIC/KVIB/DIC portal' },
      { step: 4, title: 'Interview & Approval', desc: 'District Task Force committee review' },
      { step: 5, title: 'Bank Sanction + Subsidy', desc: 'Loan approved, subsidy credited to account' },
    ],
  },
  {
    slug: 'dpiit-registration',
    title: 'DPIIT Registration',
    shortDesc: 'Get your startup recognized by DPIIT and unlock tax benefits and funding access.',
    iconName: 'FileCheck',
    color: 'indigo',
    heroDesc: 'DPIIT (Department for Promotion of Industry and Internal Trade) recognition is the gateway to India\'s startup ecosystem benefits including tax exemptions, easier compliance, and access to government funding schemes.',
    features: [
      'Tax exemption under Section 80-IAC',
      'Self-certification for 9 labor & environment laws',
      'Fast-track patent and trademark filing',
      'Access to Startup India Seed Fund Scheme',
      'Eligible for Fund of Funds',
      'Easy winding up in 90 days under IBC',
    ],
    eligibility: [
      'Entity incorporated as Private Ltd, LLP, or Partnership',
      'Incorporated not more than 10 years ago',
      'Annual turnover not exceeding ₹100 Crore',
      'Working towards innovation or scalable business model',
      'Not formed by splitting/restructuring existing business',
    ],
    process: [
      { step: 1, title: 'Entity Verification', desc: 'Ensure your business structure is eligible' },
      { step: 2, title: 'Document Preparation', desc: 'Incorporation certificate, pitch deck, website details' },
      { step: 3, title: 'Portal Application', desc: 'Apply through Startup India online portal' },
      { step: 4, title: 'Recognition Certificate', desc: 'DPIIT issues recognition number' },
      { step: 5, title: 'Benefits Activation', desc: 'Help you leverage all available benefits' },
    ],
  },
  {
    slug: 'working-capital',
    title: 'Working Capital',
    shortDesc: 'Manage cash flow effectively with flexible working capital financing solutions.',
    iconName: 'Wallet',
    color: 'cyan',
    heroDesc: 'Keep your business running smoothly with adequate working capital. We help you access overdraft facilities, cash credit, invoice financing, and other short-term funding solutions tailored to your business cycle.',
    features: [
      'Overdraft and cash credit facilities',
      'Invoice/bill discounting options',
      'Channel finance available',
      'Flexible drawdown and repayment',
      'Renewable credit lines',
      'Competitive interest rates from 11% p.a.',
    ],
    eligibility: [
      'Business operational for at least 1 year',
      'Regular bank account with transaction history',
      'GST returns filed regularly',
      'Positive net worth preferred',
      'No existing loan defaults',
    ],
    process: [
      { step: 1, title: 'Cash Flow Analysis', desc: 'Assess your working capital cycle and gaps' },
      { step: 2, title: 'Product Selection', desc: 'Choose between OD, CC, or invoice financing' },
      { step: 3, title: 'Documentation', desc: 'Bank statements, GST returns, financials' },
      { step: 4, title: 'Limit Sanctioned', desc: 'Credit limit approved by lending institution' },
      { step: 5, title: 'Drawdown', desc: 'Use funds as per business requirements' },
    ],
  },
  {
    slug: 'venture-capital',
    title: 'Venture Capital',
    shortDesc: 'Connect with VCs and angel investors for equity-based growth funding.',
    iconName: 'TrendingUp',
    color: 'rose',
    heroDesc: 'Scale your startup with venture capital and angel investment. We connect you with the right investors, help prepare your pitch, and negotiate favorable terms for equity-based funding rounds.',
    features: [
      'Angel investment from ₹25 Lakhs',
      'Series A/B/C funding connections',
      'Pitch deck and financial model preparation',
      'Investor matching based on sector',
      'Term sheet negotiation support',
      'Due diligence assistance',
    ],
    eligibility: [
      'Scalable and innovative business model',
      'Strong founding team with domain expertise',
      'Clear product-market fit or traction',
      'Addressable market size of ₹500Cr+',
      'DPIIT recognition preferred',
    ],
    process: [
      { step: 1, title: 'Startup Assessment', desc: 'Evaluate investability and readiness' },
      { step: 2, title: 'Pitch Preparation', desc: 'Craft compelling deck, model, and data room' },
      { step: 3, title: 'Investor Matching', desc: 'Connect with relevant VCs and angels' },
      { step: 4, title: 'Due Diligence', desc: 'Support throughout the DD process' },
      { step: 5, title: 'Term Sheet & Close', desc: 'Negotiate and close the funding round' },
    ],
  },
];

export function getServiceBySlug(slug) {
  return services.find((s) => s.slug === slug);
}
